"""Curated us-gaap / ifrs-full XBRL concept → 中文 dictionary (sell-side terms).

Covers the three financial statements' line items + all KPIs + common
semiconductor/AI/healthcare concepts (~155 entries). Long-tail / obscure XBRL
tags not listed here fall back to the raw English tag at runtime.

Merged into sec_facts._CONCEPT_CN at import (this dict wins on key collisions —
values here are the canonical sell-side terms). Source: docs/plans/sec-page-redesign.md §6.
"""

from __future__ import annotations

CONCEPT_CN: dict[str, str] = {
    # ===== 利润表 Income Statement =====
    "Revenues": "营业收入",
    "RevenueFromContractWithCustomerExcludingAssessedTax": "营业收入",
    "RevenueFromContractWithCustomerIncludingAssessedTax": "营业收入(含税)",
    "SalesRevenueNet": "营业收入净额",
    "SalesRevenueGoodsNet": "商品销售收入",
    "SalesRevenueServicesNet": "服务收入",
    "CostOfRevenue": "营业成本",
    "CostOfGoodsAndServicesSold": "营业成本",
    "CostOfGoodsSold": "销货成本",
    "CostOfServices": "服务成本",
    "GrossProfit": "毛利润",
    "OperatingExpenses": "营业费用合计",
    "CostsAndExpenses": "成本及费用合计",
    "ResearchAndDevelopmentExpense": "研发费用",
    "SellingGeneralAndAdministrativeExpense": "销售及管理费用",
    "GeneralAndAdministrativeExpense": "管理费用",
    "SellingAndMarketingExpense": "销售费用",
    "SellingExpense": "销售费用",
    "MarketingAndAdvertisingExpense": "营销及广告费用",
    "AmortizationOfIntangibleAssets": "无形资产摊销",
    "RestructuringCharges": "重组费用",
    "OperatingIncomeLoss": "营业利润",
    "NonoperatingIncomeExpense": "营业外净收支",
    "InterestExpense": "利息费用",
    "InterestExpenseNonoperating": "利息费用",
    "InterestIncomeExpenseNet": "利息净收支",
    "InvestmentIncomeInterest": "利息收入",
    "OtherNonoperatingIncomeExpense": "其他营业外收支",
    "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest": "税前利润",
    "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments": "税前利润",
    "IncomeTaxExpenseBenefit": "所得税费用",
    "IncomeLossFromContinuingOperations": "持续经营利润",
    "IncomeLossFromDiscontinuedOperationsNetOfTax": "终止经营损益(税后)",
    "NetIncomeLoss": "净利润",
    "ProfitLoss": "净利润",
    "NetIncomeLossAvailableToCommonStockholdersBasic": "归属普通股东净利润",
    "NetIncomeLossAttributableToNoncontrollingInterest": "少数股东损益",
    "EarningsPerShareBasic": "基本每股收益",
    "EarningsPerShareDiluted": "稀释每股收益",
    "WeightedAverageNumberOfSharesOutstandingBasic": "基本加权平均股本",
    "WeightedAverageNumberOfDilutedSharesOutstanding": "稀释加权平均股本",
    "ComprehensiveIncomeNetOfTax": "综合收益(税后)",
    "ShareBasedCompensation": "股权激励费用",
    "AllocatedShareBasedCompensationExpense": "股权激励费用",

    # ===== 资产负债表 Balance Sheet =====
    "Assets": "总资产",
    "AssetsCurrent": "流动资产合计",
    "AssetsNoncurrent": "非流动资产合计",
    "CashAndCashEquivalentsAtCarryingValue": "现金及现金等价物",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents": "现金及受限现金",
    "ShortTermInvestments": "短期投资",
    "MarketableSecuritiesCurrent": "可供出售金融资产(流动)",
    "LongTermInvestments": "长期投资",
    "AccountsReceivableNetCurrent": "应收账款净额",
    "ReceivablesNetCurrent": "应收款项净额",
    "InventoryNet": "存货净额",
    "PrepaidExpenseAndOtherAssetsCurrent": "预付费用及其他流动资产",
    "OtherAssetsCurrent": "其他流动资产",
    "PropertyPlantAndEquipmentNet": "固定资产净额",
    "PropertyPlantAndEquipmentGross": "固定资产原值",
    "OperatingLeaseRightOfUseAsset": "经营租赁使用权资产",
    "Goodwill": "商誉",
    "IntangibleAssetsNetExcludingGoodwill": "无形资产净额",
    "FiniteLivedIntangibleAssetsNet": "有限寿命无形资产净额",
    "DeferredIncomeTaxAssetsNet": "递延所得税资产",
    "OtherAssetsNoncurrent": "其他非流动资产",
    "Liabilities": "总负债",
    "LiabilitiesCurrent": "流动负债合计",
    "LiabilitiesNoncurrent": "非流动负债合计",
    "LiabilitiesAndStockholdersEquity": "负债及股东权益合计",
    "AccountsPayableCurrent": "应付账款",
    "AccountsPayableAndAccruedLiabilitiesCurrent": "应付账款及应计负债",
    "AccruedLiabilitiesCurrent": "应计负债",
    "EmployeeRelatedLiabilitiesCurrent": "应付职工薪酬",
    "ContractWithCustomerLiabilityCurrent": "合同负债(流动)",
    "DeferredRevenueCurrent": "递延收入(流动)",
    "ShortTermBorrowings": "短期借款",
    "LongTermDebtCurrent": "一年内到期长期借款",
    "LongTermDebtNoncurrent": "长期借款",
    "LongTermDebt": "长期借款",
    "OperatingLeaseLiabilityNoncurrent": "经营租赁负债(非流动)",
    "DeferredIncomeTaxLiabilitiesNet": "递延所得税负债",
    "OtherLiabilitiesNoncurrent": "其他非流动负债",
    "CommitmentsAndContingencies": "承诺及或有事项",
    "StockholdersEquity": "股东权益合计",
    "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest": "股东权益合计(含少数股东)",
    "CommonStockValue": "普通股股本",
    "AdditionalPaidInCapital": "资本公积",
    "RetainedEarningsAccumulatedDeficit": "未分配利润(累计亏损)",
    "AccumulatedOtherComprehensiveIncomeLossNetOfTax": "累计其他综合收益",
    "TreasuryStockValue": "库存股",
    "MinorityInterest": "少数股东权益",
    "CommonStockSharesOutstanding": "流通股本",
    "CommonStockSharesIssued": "已发行股本",
    "CommonStockSharesAuthorized": "授权股本",

    # ===== 现金流量表 Cash Flow Statement =====
    "NetCashProvidedByUsedInOperatingActivities": "经营活动现金流净额",
    "NetCashProvidedByUsedInOperatingActivitiesContinuingOperations": "经营活动现金流净额",
    "NetCashProvidedByUsedInInvestingActivities": "投资活动现金流净额",
    "NetCashProvidedByUsedInInvestingActivitiesContinuingOperations": "投资活动现金流净额",
    "NetCashProvidedByUsedInFinancingActivities": "融资活动现金流净额",
    "NetCashProvidedByUsedInFinancingActivitiesContinuingOperations": "融资活动现金流净额",
    "DepreciationDepletionAndAmortization": "折旧及摊销",
    "DepreciationAmortizationAndAccretionNet": "折旧摊销及增值净额",
    "DepreciationAndAmortization": "折旧及摊销",
    "Depreciation": "折旧",
    "IncreaseDecreaseInAccountsReceivable": "应收账款变动",
    "IncreaseDecreaseInInventories": "存货变动",
    "IncreaseDecreaseInAccountsPayable": "应付账款变动",
    "IncreaseDecreaseInOperatingCapital": "营运资本变动",
    "DeferredIncomeTaxExpenseBenefit": "递延所得税变动",
    "PaymentsToAcquirePropertyPlantAndEquipment": "购建固定资产支出",
    "PaymentsToAcquireProductiveAssets": "购建生产性资产支出",
    "PaymentsToAcquireBusinessesNetOfCashAcquired": "收购支出(净)",
    "PaymentsToAcquireInvestments": "购买投资支出",
    "ProceedsFromSaleMaturityAndCollectionsOfInvestments": "投资收回",
    "PaymentsForRepurchaseOfCommonStock": "股票回购",
    "PaymentsOfDividendsCommonStock": "现金分红",
    "PaymentsOfDividends": "现金分红",
    "ProceedsFromIssuanceOfLongTermDebt": "长期债务发行",
    "ProceedsFromIssuanceOfDebt": "债务发行",
    "RepaymentsOfLongTermDebt": "长期债务偿还",
    "RepaymentsOfDebt": "债务偿还",
    "ProceedsFromIssuanceOfCommonStock": "股票发行募资",
    "EffectOfExchangeRateOnCashAndCashEquivalents": "汇率变动对现金影响",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect": "现金净增加额",
    "CashAndCashEquivalentsPeriodIncreaseDecrease": "现金净增加额",

    # ===== KPI / 常用衍生与比率 =====
    "GrossMargin": "毛利率",
    "OperatingMargin": "营业利润率",
    "NetMargin": "净利率",
    "FreeCashFlow": "自由现金流",
    "FreeCashFlowMargin": "自由现金流利润率",
    "ReturnOnEquity": "净资产收益率(ROE)",
    "ReturnOnAssets": "总资产收益率(ROA)",
    "DebtToEquity": "产权比率",
    "DebtToAssets": "资产负债率",
    "CurrentRatio": "流动比率",
    "RevenueCAGR": "营收复合增速",
    "CapitalExpenditures": "资本开支",
    "EBITDA": "息税折旧摊销前利润",
    "EBIT": "息税前利润",

    # ===== 行业常见科目（半导体/AI/科技 与 医疗）=====
    "ContractWithCustomerLiabilityRevenueRecognized": "合同负债转收入",
    "ContractWithCustomerLiability": "合同负债",
    "ContractWithCustomerAssetNetCurrent": "合同资产(流动)",
    "RevenueRemainingPerformanceObligation": "未履约履约义务(在手订单)",
    "DeferredRevenueNoncurrent": "递延收入(非流动)",
    "InventoryFinishedGoodsNetOfReserves": "产成品存货净额",
    "InventoryWorkInProcessNetOfReserves": "在产品存货净额",
    "InventoryRawMaterialsNetOfReserves": "原材料存货净额",
    "ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost": "研发费用(不含在研收购)",
    "CapitalizedComputerSoftwareNet": "资本化软件净额",
    "ContractResearchAndDevelopmentExpense": "受托研发费用",
    "CollaborativeArrangementRevenue": "合作研发收入",
    "LicenseAndServicesRevenue": "授权及服务收入",
    "RoyaltyRevenue": "特许权使用费收入",
    "ProductMember": "产品收入",
    "ServiceMember": "服务收入",

    # ===== dei / 元数据 =====
    "EntityCommonStockSharesOutstanding": "流通股本",
    "EntityPublicFloat": "公众持股市值",
}
