"""LLM Wiki resolver — map a yfinance ticker to a wiki company page.

LLM Wiki at `~/Documents/LLM Wiki/Wiki/companies/*.md`.

Filename conventions observed:
- HK: zero-padded 5-digit code, e.g. `01093-cspc-pharma.md` for `1093.HK`
- US: lowercase ticker prefix, e.g. `lly-eli-lilly.md` for `LLY`
- CN: 6-digit code, e.g. `300760-mindray.md` for `300760.SZ`

Returns parsed structure: frontmatter (Summary / Thesis / Rating / TP / Sources /
Last updated) + body sections (财务快照, 核心投资逻辑, 催化剂, 风险点, 管理层动态,
矛盾与待验证, Related pages).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path

# Local internal wiki (full memo, analyst rating / TP / source PDF refs intact).
# Only available on George's Mac.
_INTERNAL_WIKI_ROOT = Path.home() / "Documents" / "LLM Wiki" / "Wiki" / "companies"

# Public sanitized wiki — shipped in the repo, available on Streamlit Cloud.
# Generated by `jobs/export_wiki_public.py` (weekly cron).
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_PUBLIC_WIKI_ROOT = _REPO_ROOT / "data" / "wiki" / "companies"


def _wiki_roots() -> list[tuple[Path, bool]]:
    """Resolution order: internal first (richer), public second (Cloud fallback).

    Returns [(path, is_sanitized), ...] for each existing root.
    """
    roots: list[tuple[Path, bool]] = []
    if _INTERNAL_WIKI_ROOT.exists():
        roots.append((_INTERNAL_WIKI_ROOT, False))
    if _PUBLIC_WIKI_ROOT.exists():
        roots.append((_PUBLIC_WIKI_ROOT, True))
    return roots


# Back-compat alias.
WIKI_ROOT = _INTERNAL_WIKI_ROOT


@dataclass
class WikiPage:
    """Parsed wiki company page."""
    ticker: str
    file_path: Path
    title: str = ""
    summary: str = ""
    thesis: str = ""
    rating: str = ""
    tp: str = ""
    sectors: list[str] = field(default_factory=list)
    last_updated: str = ""
    sources: str = ""
    sections: dict[str, str] = field(default_factory=dict)
    raw: str = ""
    is_sanitized: bool = False  # True when served from public-sanitized data/wiki/

    @property
    def exists(self) -> bool:
        return self.file_path.exists()


# Explicit market-suffix → wiki filename convention. Don't lowercase non-CN
# numeric codes — 北交所 836255.BJ would become '836255.bj-' under a naive
# .lower() fallback. Wiki convention: keep the numeric code as-is for any
# Chinese / HK / TW / SG exchange, and lowercase only for US-style alpha tickers.
_NUMERIC_CODE_SUFFIXES = {
    "HK",         # 港交所 — zero-pad to 5 digits (1093 → 01093) per wiki conv
    "SS", "SH",   # 上交所 (yfinance .SS; Bloomberg/Wind .SH)
    "SZ",         # 深交所
    "BJ",         # 北交所
    "TW",         # 台湾交易所
    "TWO",        # 台湾 OTC (上柜)
    "SI",         # 新加坡
    "KS", "KQ",   # KOSPI / KOSDAQ
    "T",          # 东证 (Tokyo)
}


def _candidate_stems(ticker: str) -> list[str]:
    """Return list of filename-prefix candidates to glob for.

    Examples:
        1093.HK   → ['01093-', '1093-']
        300760.SZ → ['300760-']
        836255.BJ → ['836255-']
        2330.TW   → ['02330-', '2330-']
        LLY       → ['lly-']
        688575.SS → ['688575-']
    """
    if not ticker:
        return []
    ticker = ticker.strip()
    candidates: list[str] = []
    if "." in ticker:
        code, suffix = ticker.split(".", 1)
        code = code.strip()
        suffix = suffix.strip().upper()
        if suffix == "HK" or suffix == "TW":
            # 港股 / 台股 wiki convention: zero-pad to 5 digits when shorter,
            # but also try the raw form to be tolerant.
            if code.isdigit() and len(code) < 5:
                candidates.append(f"{code.zfill(5)}-")
            candidates.append(f"{code}-")
        elif suffix in _NUMERIC_CODE_SUFFIXES:
            candidates.append(f"{code}-")
        else:
            # Unknown suffix: best-effort fallback. Try the raw code first, then
            # the lowercase combined form so we don't silently match the wrong file.
            candidates.append(f"{code}-")
            candidates.append(f"{ticker.lower()}-")
    else:
        candidates.append(f"{ticker.lower()}-")
    # De-duplicate while preserving order.
    seen: set[str] = set()
    return [c for c in candidates if not (c in seen or seen.add(c))]


def _resolve_path(ticker: str) -> tuple[Path, bool] | None:
    """Return (file_path, is_sanitized) for the best match across wiki roots."""
    for root, sanitized in _wiki_roots():
        for stem in _candidate_stems(ticker):
            matches = sorted(root.glob(f"{stem}*.md"))
            if matches:
                return matches[0], sanitized
    return None


_FRONTMATTER_KEYS = {
    "Summary": "summary",
    "Thesis": "thesis",
    "Rating": "rating",
    "TP": "tp",
    "Last updated": "last_updated",
    "Sources": "sources",
}


def _parse_frontmatter_line(line: str, page: WikiPage) -> None:
    """Match lines like `**Summary**: xxx` or `**Rating**: BUY | **TP**: USD 964`."""
    # Multiple key/value tokens may share one line (Rating + TP).
    for label, attr in _FRONTMATTER_KEYS.items():
        # Match `**Label**: value` up to next `**` or end of line.
        pattern = rf"\*\*{re.escape(label)}\*\*\s*:\s*([^*]+?)(?=\s*\*\*|\s*$)"
        match = re.search(pattern, line)
        if match:
            current = getattr(page, attr) or ""
            value = match.group(1).strip().rstrip("|").strip()
            if not current and value:
                setattr(page, attr, value)
    # Sectors: `**Sectors**: [[a]], [[b]]`
    sec_match = re.search(r"\*\*Sectors\*\*\s*:\s*(.+)", line)
    if sec_match and not page.sectors:
        page.sectors = [s.strip("[]` ") for s in re.findall(r"\[\[([^\]]+)\]\]", sec_match.group(1))]


def _parse_page(ticker: str, path: Path) -> WikiPage:
    page = WikiPage(ticker=ticker, file_path=path)
    text = path.read_text(encoding="utf-8")
    page.raw = text
    lines = text.splitlines()

    # Title is the first `# ...` line.
    for line in lines[:5]:
        if line.startswith("# "):
            page.title = line.lstrip("# ").strip()
            break

    # Frontmatter region: from start until the first `---` separator (or first `## ` section).
    in_frontmatter = True
    body_lines: list[str] = []
    current_section: str | None = None
    section_buf: dict[str, list[str]] = {}

    for line in lines:
        stripped = line.strip()
        if in_frontmatter:
            if stripped == "---":
                in_frontmatter = False
                continue
            if stripped.startswith("## "):
                in_frontmatter = False
                # fall through to section handling
            else:
                if stripped.startswith("**"):
                    _parse_frontmatter_line(line, page)
                continue
        if not in_frontmatter:
            if stripped.startswith("## "):
                current_section = stripped[3:].strip()
                section_buf[current_section] = []
            elif current_section is not None:
                section_buf[current_section].append(line)
            body_lines.append(line)

    page.sections = {k: "\n".join(v).strip() for k, v in section_buf.items()}
    return page


@lru_cache(maxsize=256)
def find_wiki(ticker: str) -> WikiPage | None:
    """Return parsed WikiPage for ticker, or None if no wiki entry exists."""
    if not ticker:
        return None
    resolved = _resolve_path(ticker)
    if resolved is None:
        return None
    path, is_sanitized = resolved
    try:
        page = _parse_page(ticker, path)
        page.is_sanitized = is_sanitized
        return page
    except Exception:
        # Wiki parse should never crash the page.
        return None


def has_wiki(ticker: str) -> bool:
    return _resolve_path(ticker) is not None
