#!/bin/bash
# Weekly wiki sync — runs export_wiki_public.py, commits + pushes if changed.
# Invoked by ~/Library/LaunchAgents/com.gcc.invest-dashboard.wiki-sync.plist
# every Sunday at 20:00 local time.
#
# Manual run:  bash scripts/wiki_weekly_sync.sh
# Install cron: see scripts/install_launchd_wiki.sh

set -uo pipefail

REPO="/Users/gcc/invest-dashboard"
LOG_DIR="$REPO/.omc/logs"
LOG_FILE="$LOG_DIR/wiki_weekly.log"

mkdir -p "$LOG_DIR"
exec >> "$LOG_FILE" 2>&1

echo "===== $(date +'%Y-%m-%d %H:%M:%S %Z') · wiki_weekly_sync.sh start ====="

cd "$REPO" || { echo "FATAL: cannot cd to $REPO"; exit 1; }

# Ensure uv is in PATH (launchd PATH is minimal).
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

# 1. Pull latest so we don't push on a stale base.
git pull --rebase --autostash origin main || { echo "git pull failed, abort"; exit 1; }

# 2. Run the sanitization export.
echo "--- running export_wiki_public.py ---"
uv run python jobs/export_wiki_public.py || { echo "export failed, abort"; exit 1; }

# 3. Detect changes in data/wiki/.
if git diff --quiet -- data/wiki/; then
  echo "no wiki changes — nothing to commit"
  echo "===== $(date +'%Y-%m-%d %H:%M:%S') · done (no-op) ====="
  echo
  exit 0
fi

# 4. Commit + push.
git add data/wiki/
TS=$(date +'%Y-%m-%d')
git commit -m "chore(wiki): weekly sanitized wiki export ($TS)

Generated by scripts/wiki_weekly_sync.sh via launchd.
Source: ~/Documents/LLM Wiki/Wiki/companies/
Strip rules: jobs/export_wiki_public.py" || { echo "git commit failed"; exit 1; }

git push origin main || { echo "git push failed (network?). Will retry next week."; exit 1; }

echo "===== $(date +'%Y-%m-%d %H:%M:%S') · pushed successfully ====="
echo
